config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root :to =>"homes#top"
  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
  	get 'followings' => 'relationships#followings', as: 'followings'
  	get 'followers' => 'relationships#followers', as: 'followers'
    get "search", to: "users#search"
  end
  resources :groups, except: [:destroy] do
    get 'join' => 'groups#join'
    delete 'leave' => 'groups#leave'
    get 'notice' => 'groups#new_mail'
    post 'send' => 'groups#send_mail'
  end
  get '/search', to: 'searches#search'

  resources :chats, only: [:show, :create]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
  has_one_attached :image

  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users

  validates :name, presence: true
  validates :introduction, presence: true

  def is_owned_by?(user)
    owner.id == user.id
  end

  def get_image(weight, height)
    unless self.image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    self.image.variant(resize_to_fill: [weight,height]).processed
  end

  def get_owner
    users.find(owner_id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_owner, only: [:edit, :update]
  
  def new
    @group = Group.new
  end

  def index
    @groups = Group.all
    @book = Book.new
  end

  def show
    @group = Group.find(params[:id])
  end

  def edit
    @group = Group.find(params[:id])
  end

  def create
    @group = Group.new(group_params)
    @group.owner_id = current_user.id
    @group.users << current_user
    if @group.save
      redirect_to groups_path
    else
      render 'new'
    end
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to groups_path
    else
      render 'new'
    end
  end

  def join
    @group = Group.find(params[:group_id])
    @group.users << current_user
    redirect_to groups_path
  end

  def leave
    @group = Group.find(params[:group_id])
    @group.users.delete(current_user)
    redirect_to groups_path
  end

  def new_mail
    @group = Group.find(params[:group_id])
  end

  def send_mail
    @group = Group.find(params[:group_id])
    @mail_title = params[:mail_title]
    @mail_body = params[:mail_body]

    event = {
      :group => @group,
      :title => @mail_title,
      :body => @mail_body
    }

    NoticeMailer.send_notification(event)
  end

  private
  def group_params
    params.require(:group).permit(:name, :introduction, :image)
  end

  def ensure_correct_owner
    group = Group.find(params[:id])
    unless group.owner_id == current_user.id
      redirect_to groups_path
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with model: group do |f| %>
  <div class="mb-4">
    <%= f.label :name, "グループ名", class: "form-label" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="mb-4">
    <%= f.label :introduction, "紹介文", class: "form-label" %>
    <%= f.text_area :introduction, class: "form-control" %>
  </div>

  <div class="mb-4">
    <%= f.label :image, "グループ画像", class: "form-label" %><br>
    <%= f.file_field :image, accept: "image/*" %>
  </div>

  <%= f.submit "Create Group", class: "btn btn-primary" %>
<% end %>

app/views/groups/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>グループ名</th>
      <th>紹介文</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% groups.each do |group| %>
      <tr>
        <td><%= link_to group_path(group.id) do %>
          <%= image_tag group.get_image(80,80) %>
          <% end %>
        </td>
        <td><%= link_to group.name, group_path(group.id) %></td>
        <td><%= group.introduction %></td>
        <% if group.owner_id == current_user.id %>
          <td><%= link_to "Edit", edit_group_path(group.id), class: "btn btn-success" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/groups/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-8 mx-auto">
      <h1 class="mb-4">Editing Group</h1>
      <%= render 'form', group: @group %>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Grous</h2>
      <%= render 'index', groups: @groups %>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-8 mx-auto">
      <h1 class="mb-4">Create Group</h1>
      <%= render 'form', group: @group %>
    </div>
  </div>
</div>

app/views/groups/new_mail.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>Event Mail</h2>
      <%= form_with url:group_send_path(@group), method: :post, local: true do |f| %>

        <div class="form-group">
          <%= f.label :mail_title, 'title' %>
          <%= f.text_field :mail_title, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :mail_body, 'content' %>
          <%= f.text_area :mail_body, class: "form-control" %>
        </div>

        <div>
          <%= f.submit "送信", class: "btn btn-success" %>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/groups/send_mail.html.erb
<div class="container d-flex flex-column align-items-center text-left">
  <div>
    <h3 class="mb-3">送信が完了しました。</h3>
    <p class="mb-1">内容は以下の通りです。</p>
    <div>
      [タイトル]<p class="font-weight-bold"><%= @mail_title %></p>
    </div>
    <div>
      [本文]<p class="font-weight-bold"><%= safe_join(@mail_body.split("\n"),tag(:br)) %></p>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @group.get_owner %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: Book.new %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Group detail</h2>
  		<table class='table'>
        <thead>
          <tr>
            <th></th>
            <th>グループ名</th>
            <th>紹介文</th>
            <th>メンバー</th>
            <th colspan="2"></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <%= image_tag @group.get_image(100,100) %><br>
            </td>
            <td><%= @group.name %></td>
            <td><%= @group.introduction %></td>
            <td>
              <% @group.users.each do |user| %>
                <p class="mb-0"><%= user.name %></p>
              <% end %>
            </td>
            <% if @group.owner_id == current_user.id %>
              <td><%= link_to 'Edit', edit_group_path(@group), class: "btn btn-success" %></td>
            <% elsif @group.users.include?(current_user) %>
              <td><%= link_to 'Leave this group', group_leave_path(@group), method: :delete, class: "btn btn-danger" %></td>
            <% else %>
              <td><%= link_to 'Join This Group', group_join_path(@group), class: "btn btn-success" %></td>
            <% end %>
            <% if @group.owner_id == current_user.id %>
              <td><%= link_to "Notice an Event", group_notice_path(@group), class: "btn btn-info" %></td>
            <% end %>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>